export const TEAM_COLORS = [0x3a86ff, 0xff4d5e];
export const TEAM_NAMES = ['BLUE', 'RED'];
export const TEAM_CSS = ['#3a86ff', '#ff4d5e'];

export const CLASS_ORDER = ['berserker', 'mage', 'assassin', 'sniper', 'engineer', 'gunslinger'];

export const CLASSES = {
  berserker: {
    id: 'berserker',
    name: 'Berserker',
    role: 'Bruiser',
    hp: 300,
    speed: 5.6,
    hat: 'horns',
    accent: '#c0392b',
    weapon: 'Minigun',
    ability: 'Shoulder Charge',
    superName: 'Rage',
    superDuration: 12,
    blurb: 'Spin up the minigun and shred. Charges Rage by dealing AND taking damage.',
    details: [
      'LMB: Minigun (0.6s spin-up) / RMB: spin without firing',
      'E: Shoulder Charge, knocks enemies back',
      'Q: RAGE. Fists only, +30% speed, half damage taken, huge jumps',
      'Rage + RMB in mid-air: SLAM the ground',
    ],
  },
  mage: {
    id: 'mage',
    name: 'Mage',
    role: 'Caster',
    hp: 150,
    speed: 6.4,
    hat: 'wizard',
    accent: '#7b5cff',
    weapon: 'Wand',
    ability: 'Blink',
    superName: 'Meteor',
    superDuration: 0,
    usesMana: true,
    blurb: 'No super bar. A mana pool feeds four spell slots: bolt, self-heal, a warding force field, and a Meteor.',
    details: [
      '1 Arcane Bolt / 2 Mend (heal yourself) / 3 Arcane Ward / 4 Meteor',
      'Arcane Ward follows you: heals allies inside, burns and repels enemies',
      'LMB: cast selected spell / scroll or 1-4: select / E: Blink',
      'Q: Meteor, needs full mana and a 3s channel',
    ],
  },
  assassin: {
    id: 'assassin',
    name: 'Assassin',
    role: 'Stealth',
    hp: 125,
    speed: 7.4,
    hat: 'headband',
    accent: '#2d2a3e',
    weapon: 'Katana',
    ability: 'Stalk',
    superName: 'Shadow Strike',
    superDuration: 10,
    blurb: 'Crouch-stalk while cloaked and backstab. Cloaked backstabs always kill.',
    details: [
      'LMB: Katana slash / RMB: dash-slash Lunge / Space x2: double jump',
      'E: Stalk. Crouch and creep at half speed, staying cloaked',
      'Standing still 1.5s also cloaks. Uncloaked backstab: 75% of max HP',
      'Q: SHADOW STRIKE. Teleport behind the nearest enemy and kill; each kill chains another teleport (75% strikes)',
    ],
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    role: 'Marksman',
    hp: 150,
    speed: 6.3,
    hat: 'beanie',
    accent: '#4f772d',
    weapon: 'Sniper Rifle',
    ability: 'Grapple',
    superName: 'Wallhack',
    superDuration: 12,
    blurb: 'One headshot or two body shots kills anyone. Grapple onto rooftops.',
    details: [
      'LMB: Fire / RMB: Scope (no-scopes are inaccurate)',
      'E: Grapple hook (buildings only, keeps momentum)',
      'Q: WALLHACK. See enemy outlines through walls',
    ],
  },
  engineer: {
    id: 'engineer',
    name: 'Engineer',
    role: 'Builder',
    hp: 175,
    speed: 6.2,
    hat: 'hardhat',
    accent: '#f4a300',
    weapon: 'Scrap Shotgun',
    ability: 'Build',
    superName: 'Drone Strike',
    superDuration: 12,
    blurb: 'Spend scrap on a turret, cover wall and jump pad. Pilot a kamikaze drone.',
    details: [
      'LMB: Shotgun / RMB: Wrench (repairs builds)',
      'E: Build mode. 1 Turret / 2 Wall / 3 Jump Pad, LMB to place',
      'Q: DRONE. Fly it (Space up, Shift down), LMB shoot',
      'Ram enemies to detonate, RMB kamikaze boost',
    ],
  },
  gunslinger: {
    id: 'gunslinger',
    name: 'Gunslinger',
    role: 'Duelist',
    hp: 175,
    speed: 6.8,
    hat: 'cap',
    accent: '#d35400',
    weapon: 'Dual Revolvers',
    ability: 'Dodge Roll',
    superName: 'Hair Trigger',
    superDuration: 10,
    blurb: 'Alternating revolvers whose bullets ricochet. Knives on the side.',
    details: [
      'LMB: Revolvers (ricochet once) / RMB: Throwing knife',
      'E: Dodge roll. I-frames and reload (dodging a hit = full reload)',
      'Q: HAIR TRIGGER. Auto-lock, always-hit double-damage crits',
      'No fire-rate cap during Hair Trigger. Click fast!',
    ],
  },
};

export const BOT_NAMES = [
  'Twiggy', 'Matchstick', 'Noodle', 'Beanpole', 'Lanky', 'Doodle', 'Scribbles', 'Slim',
  'Chopstick', 'Pencil Pete', 'Toothpick', 'Pretzel', 'Sticky Vicky', 'Stilts', 'Wishbone',
  'Linus', 'Scrawl', 'Stroke', 'Sketchy', 'Q-Tip',
];
